### ISSUE TITLE
MCS connection failure 

### ISSUE THREAD

**Issue by sacketty** [CydeSwype/electron-fcm-demo#3]
Hi,
I tried de demo but I got stuck after 'starting service and registering a client'.
The console output showed:
`Error while communicating with MCS server
{ Error: connect ETIMEDOUT 64.233.184.188:5228
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '64.233.184.188',
  port: 5228 }
MCS socket closed after 1451 minutes`

Any clue ?

**Comment by sacketty** [comment]
I finally found that it was just a proxy/firewall problem.
